FROM python:3.12-slim

WORKDIR /exhibition-exp

RUN set -eux && \
  	apt-get update &&  \
  	apt-get upgrade -y && \
  	apt-get install -y --no-install-recommends \
        build-essential \  
        libpq5 && \
    rm -rf /var/lib/apt/lists/* && \
	groupadd \
          --system \
       exhibition-exp && \
      useradd \
          --system \
      exhibition-exp \
          -g \
      exhibition-exp